### ISSUE TITLE
What do u used to open it??

### ISSUE THREAD

**Issue by artayasa** [Tenebryo/servo-config-tool#1]
What do u used to open it on windows sir? I dont see the exe file sir. Thank u, i hope u can help me thank u🙏

**Comment by Tenebryo** [comment]
I don't provide a precompiled binary or exe, you need to compile the program yourself using the rust compiler. 

once you install the rust compiler, it should work just by running `cargo run --release` (that will also create the exe in the `./target/release/` folder)
